// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFnJbo3lFm03rRAkzQ55WDZAcCTLSC5Qo',
    appId: '1:1035100738614:web:7d8557aabdb2055ce5f497',
    messagingSenderId: '1035100738614',
    projectId: 'premiere-attendance',
    authDomain: 'premiere-attendance.firebaseapp.com',
    storageBucket: 'premiere-attendance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnHaKJSSGF2dkoWaZyh3PBlUnhscoVXiw',
    appId: '1:1035100738614:android:db18082fbcbeccf1e5f497',
    messagingSenderId: '1035100738614',
    projectId: 'premiere-attendance',
    storageBucket: 'premiere-attendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHqerQoIBoeTZ7pBxAgmQT9UdWxcxa_Gg',
    appId: '1:1035100738614:ios:5c31312168a3065fe5f497',
    messagingSenderId: '1035100738614',
    projectId: 'premiere-attendance',
    storageBucket: 'premiere-attendance.appspot.com',
    iosBundleId: 'com.pefattendance.pefAttendanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHqerQoIBoeTZ7pBxAgmQT9UdWxcxa_Gg',
    appId: '1:1035100738614:ios:5c31312168a3065fe5f497',
    messagingSenderId: '1035100738614',
    projectId: 'premiere-attendance',
    storageBucket: 'premiere-attendance.appspot.com',
    iosBundleId: 'com.pefattendance.pefAttendanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFnJbo3lFm03rRAkzQ55WDZAcCTLSC5Qo',
    appId: '1:1035100738614:web:04fe8f530a58e3d9e5f497',
    messagingSenderId: '1035100738614',
    projectId: 'premiere-attendance',
    authDomain: 'premiere-attendance.firebaseapp.com',
    storageBucket: 'premiere-attendance.appspot.com',
  );
}
